### ISSUE TITLE
Pruebas presentes, pero el documento de diseño es sólo un esqueleto

### ISSUE THREAD

**Issue by lauramcastro** [christianpalou/vvs#2]
Lleváis retraso completando el mínimo que se pedía para la segunda semana: el documento `test.txt` no tiene información realmente (es sólo un esqueleto-plantilla), aunque tenéis pruebas implementadas (asumo que pre-existentes). No os despistéis, el trabajo también se valora semana a semana.

**Comment by christianpf5** [comment]
Hecho para el BlogServiceTest.
Estuvimos muy liados, ya nos ponemos al día.
